using DbBackupManager.Application.BackupTasks;
using DbBackupManager.Domain.BackupTasks;

namespace DbBackupManager.Application.Tests;

public sealed record P57InvalidEvidenceCase(
    string Name,
    Guid TaskId,
    Guid BackupAttemptId,
    BackupTaskStage Stage,
    DateTimeOffset ObservedAtUtc,
    BackupReconciliationConclusion Conclusion,
    BackupArtifactObservation Artifact,
    TargetBackupObservation TargetBackup,
    BackupVerificationObservation Verification,
    string ReasonCode,
    long? SourceLengthBytes);

public sealed record P57ValidNonSuccessEvidenceCase(
    BackupTaskStage Stage,
    BackupReconciliationConclusion Conclusion,
    BackupArtifactObservation Artifact,
    TargetBackupObservation TargetBackup,
    BackupVerificationObservation Verification,
    string ReasonCode,
    long? SourceLengthBytes);

internal static class P57ReconciliationEvidenceCases
{
    internal static readonly Guid TaskId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
    internal static readonly Guid AttemptId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb");
    internal static readonly DateTimeOffset Utc = new(2026, 9, 14, 2, 0, 0, TimeSpan.Zero);

    public static TheoryData<P57InvalidEvidenceCase> InvalidConstructors { get; } = new()
    {
        Invalid(
            "empty-task-id",
            Guid.Empty,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "empty-attempt-id",
            TaskId,
            Guid.Empty,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "non-utc-time",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc.ToOffset(TimeSpan.FromHours(8)),
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "undefined-conclusion",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            (BackupReconciliationConclusion)0,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "undefined-artifact",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            (BackupArtifactObservation)0,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "undefined-target",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            (TargetBackupObservation)99,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "undefined-verification",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            (BackupVerificationObservation)0,
            "probe.unknown"),
        Invalid(
            "undefined-stage",
            TaskId,
            AttemptId,
            (BackupTaskStage)0,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown"),
        Invalid(
            "empty-reason",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            string.Empty),
        Invalid(
            "uppercase-reason",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "Backup.unknown"),
        Invalid(
            "reason-with-slash",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe/unknown"),
        Invalid(
            "reason-too-long",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            new string('a', 101)),
        Invalid(
            "zero-length",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "probe.unknown",
            0),
        Invalid(
            "negative-length",
            TaskId,
            AttemptId,
            BackupTaskStage.VerifyLocal,
            Utc,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.PresentChanging,
            TargetBackupObservation.InProgress,
            BackupVerificationObservation.Indeterminate,
            "probe.changing",
            -1),
        Invalid(
            "verify-success-without-verify",
            TaskId,
            AttemptId,
            BackupTaskStage.VerifyLocal,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.NotAttempted,
            "verify.not_attempted",
            1024),
        Invalid(
            "transfer-success-without-length",
            TaskId,
            AttemptId,
            BackupTaskStage.Transfer,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.NotAttempted,
            "transfer.missing_length"),
        Invalid(
            "cleanup-success-with-present-file",
            TaskId,
            AttemptId,
            BackupTaskStage.Cleanup,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.NotAttempted,
            "cleanup.source_present",
            8),
        Invalid(
            "backup-success-missing-file",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.Missing,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.NotAttempted,
            "backup.missing"),
        Invalid(
            "backup-success-target-not-found",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.NotFound,
            BackupVerificationObservation.NotAttempted,
            "backup.target_missing"),
        Invalid(
            "backup-success-with-verify",
            TaskId,
            AttemptId,
            BackupTaskStage.Backup,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.Succeeded,
            "backup.skipped_verify",
            1024),
        Invalid(
            "verify-success-without-length",
            TaskId,
            AttemptId,
            BackupTaskStage.VerifyLocal,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.Succeeded,
            "verify.missing_length"),
        Invalid(
            "verify-success-changing-file",
            TaskId,
            AttemptId,
            BackupTaskStage.VerifyLocal,
            Utc,
            BackupReconciliationConclusion.Succeeded,
            BackupArtifactObservation.PresentChanging,
            TargetBackupObservation.CompletedMatching,
            BackupVerificationObservation.Succeeded,
            "verify.changing",
            1024),
    };

    public static TheoryData<P57ValidNonSuccessEvidenceCase> ValidNonSuccess { get; } = new()
    {
        new(
            BackupTaskStage.Backup,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Missing,
            TargetBackupObservation.NotFound,
            BackupVerificationObservation.NotAttempted,
            "backup.missing",
            null),
        new(
            BackupTaskStage.Backup,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.PresentChanging,
            TargetBackupObservation.InProgress,
            BackupVerificationObservation.Indeterminate,
            "backup.changing",
            4096),
        new(
            BackupTaskStage.VerifyLocal,
            BackupReconciliationConclusion.ConfirmedFailed,
            BackupArtifactObservation.IdentityMismatch,
            TargetBackupObservation.IdentityMismatch,
            BackupVerificationObservation.ConfirmedFailed,
            "verify.identity_mismatch",
            8),
        new(
            BackupTaskStage.VerifyLocal,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.Indeterminate,
            "verify.probe_interrupted",
            null),
        new(
            BackupTaskStage.Transfer,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.Unknown,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "reconciliation.remote_copy_unconfirmed",
            4096),
        new(
            BackupTaskStage.Cleanup,
            BackupReconciliationConclusion.Inconclusive,
            BackupArtifactObservation.PresentStable,
            TargetBackupObservation.Unknown,
            BackupVerificationObservation.NotAttempted,
            "reconciliation.cleanup_source_remains",
            4096),
    };

    private static P57InvalidEvidenceCase Invalid(
        string name,
        Guid taskId,
        Guid backupAttemptId,
        BackupTaskStage stage,
        DateTimeOffset observedAtUtc,
        BackupReconciliationConclusion conclusion,
        BackupArtifactObservation artifact,
        TargetBackupObservation targetBackup,
        BackupVerificationObservation verification,
        string reasonCode,
        long? sourceLengthBytes = null)
    {
        return new(
            name,
            taskId,
            backupAttemptId,
            stage,
            observedAtUtc,
            conclusion,
            artifact,
            targetBackup,
            verification,
            reasonCode,
            sourceLengthBytes);
    }
}
