<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DbBackupManager.Application\DbBackupManager.Application.csproj" />
    <ProjectReference Include="..\DbBackupManager.Domain\DbBackupManager.Domain.csproj" />
  </ItemGroup>
</Project>
